---
- name: install python 2
  apt:
    name:
      - python
      - python-dev
      - python-virtualenv
      - python-setuptools
      - python-six
      - python-pip
    state: present

- name: install python 3
  apt:
    name:
      - python3
      - python3-dev
      - python3-virtualenv
      - python3-setuptools
      - python3-six
      - python3-pip
    state: present
  when: python3_enabled|bool
