---
- name: install python 2
  yum:
    name:
      - python
      - python-pip
      - python-devel
      - python-setuptools
      - python-virtualenv
    state: present
  when: python2_enabled|bool

- name: install python 3
  yum:
    name:
      - python34
      - python34-pip
      - python34-devel
      - python34-setuptools
    state: present
  when: python3_enabled|bool
