---
- name: install python 2
  yum: name={{ item }} state=present
  with_items:
      - python
      - python-pip
      - python-devel
      - python-setuptools
      - python-virtualenv

- name: install python 3
  yum: name={{ item }} state=present
  when: python3_enabled
  with_items:
      - python34
      - python34-pip
      - python34-devel
      - python34-setuptools
