---
- name: install python 2
  apt: name={{ item }} state=present
  with_items:
      - python
      - python-dev
      - python-virtualenv
      - python-setuptools
      - python-six
      - python-pip

- name: install python 3
  apt: name={{ item }} state=present
  when: python3_enabled
  with_items:
      - python3
      - python3-dev
      - python3-virtualenv
      - python3-setuptools
      - python3-six
      - python3-pip
