---
- name: install python 2
  apt:
    name: "{{ python2_debian_packages if ansible_distribution_version is version('20.04', '>=') else python2_debian_old_packages }}"
    state: present
  when: python2_enabled|bool

- name: install python 3
  apt:
    name: "{{ python3_debian_packages if ansible_distribution_version is version('20.04', '>=') else python3_debian_old_packages }}"
    state: present
  when: python3_enabled|bool
